checks:
    php: true
filter: {  }
coding_style:
    php:
        indentation:
            general:
                use_tabs: false
        spaces:
            around_operators:
                negation: true
                concatenation: true
